name: univ_schedule
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.0.0
  table_calendar: ^3.0.1
  provider: ^5.0.0
  intl: ^0.17.0
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  cloud_firestore: ^1.0.7
  intro_slider: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: DonghyunKo
      fonts:
        - asset: fonts/Stylish-Regular.ttf
    - family: DonghyunEn
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
